name: Reset Tutorial

on:
  workflow_dispatch:

jobs:
  reset:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-reset.yml@main
    with:
      tutorial-name: Secure Coding Web API
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
